id: I4D9AE76A
default_language: zh
source: https://www2.hf.uio.no/polyglotta/index.php?page=library&bid=2
initial_creation_type: input
imported: 2023-02-09 14:42:11.681823
last_modified: 2023-02-09 14:42:11.681941
source_metadata:
  title: 'BA: Gaṇḍavyūhasūtra'
  language: zh
bases:
  744E:
    base_file: 744E.txt
    order: 1
copyright:
  status: Unknown
  notice: ''
